name: Tommy Vedvik
favicon: null
layout_spectrum: 0.02254170016385615
typography_spectrum: 0.4574180890340358
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.15754585899412632
  lightness: 0.4230936747044325
  saturation: 0.18374731275252998
  rhythmicContrast: 0.06287208432331681
purpose: []
